node_role: ce
customer_as: 65201
customer_router_id: 10.2.0.2
pe_neighbor_ip: 10.2.0.1
pe_neighbor_as: 65000
ce_link_interface: Ethernet1
ce_link_ip: 10.2.0.2/30
lan_interface: Ethernet2
lan_ip: 10.20.1.1/24
lan_prefix: 10.20.1.0/24
