---
node_role: p
router_id: 10.255.0.12
loopback0: 10.255.0.12/32

ospf_interfaces:
  - name: Ethernet1
    address: 10.0.0.1/31
  - name: Ethernet2
    address: 10.0.0.8/31
  - name: Ethernet3
    address: 10.0.0.10/31
  - name: Ethernet4
    address: 10.0.0.12/31
expected_ospf_neighbors: 4
