---
node_role: p
router_id: 10.255.0.11
loopback0: 10.255.0.11/32

ospf_interfaces:
  - name: Ethernet1
    address: 10.0.0.0/31
  - name: Ethernet2
    address: 10.0.0.2/31
  - name: Ethernet3
    address: 10.0.0.4/31
  - name: Ethernet4
    address: 10.0.0.6/31
expected_ospf_neighbors: 4
