---
node_role: pe
router_id: 10.255.0.21
loopback0: 10.255.0.21/32

ospf_interfaces:
  - name: Ethernet1
    address: 10.0.0.3/31
  - name: Ethernet2
    address: 10.0.0.9/31
expected_ospf_neighbors: 2
