---
node_role: pe
router_id: 10.255.0.21
loopback0: 10.255.0.21/32

ospf_interfaces:
  - name: Ethernet1
    address: 10.0.0.3/31
  - name: Ethernet2
    address: 10.0.0.9/31
expected_ospf_neighbors: 2
bgp_rr_address: 10.255.0.11

l3vpn_pe_ce_links:
  - vrf: TENANT_1
    interface: Ethernet3
    ip: 10.1.0.1/30
    neighbor_ip: 10.1.0.2
    neighbor_as: 65101
  - vrf: TENANT_2
    interface: Ethernet4
    ip: 10.2.0.1/30
    neighbor_ip: 10.2.0.2
    neighbor_as: 65201

l3vpn_remote_routes:
  - vrf: TENANT_1
    prefix: 10.10.2.0/24
    forbidden_prefix: "10.20."
  - vrf: TENANT_2
    prefix: 10.20.2.0/24
    forbidden_prefix: "10.10."
