---
ansible_connection: ansible.netcommon.httpapi
ansible_network_os: arista.eos.eos
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_httpapi_port: 443
ansible_user: admin
ansible_password: admin
ospf_process_id: 1
ospf_area: 0.0.0.0
ansible_become: true
ansible_become_method: enable
bgp_as: 65000
